[package]
name = "rustdt-json_rpc"
version = "0.3.0"
authors = ["Bruno Medeiros <bruno.do.medeiros@gmail.com>"]

description = "A JSON-RPC library for Rust"
repository = "https://github.com/RustDT/rustdt-json_rpc"
documentation = "https://docs.rs/rustdt-json_rpc"
license = "Apache-2.0"
keywords = ["rustdt", "jsonrpc", "json-rpc", "rpc"]

[dependencies]
rustdt_util = "0.2.3"
log = "0.4.11"
serde = "1.0"
serde_json = "1.0"
futures = "0.1.3"

[dev-dependencies]
rustdt_util = { version = "0.2.3", features = ["test_utils"] }
env_logger = "0.7.1"

[lib]
name = "jsonrpc"
path = "src/jsonrpc.rs"
